### ISSUE TITLE
A setting for next special round

### ISSUE THREAD

**Issue by llPh3NiXll** [5and5/BO1-StratTester#22]
Hello,

Sometimes, it can be useful to practice a dog round or a monkey round depending on where the player is. It could also help people to find some very good dog spawn controls on Der Riese for instance.

That's why I think a setting to flag a round as a dog round may be useful, or just a console command maybe ?

Thanks !

**Comment by TTS4life** [comment]
Definitely an overdue feature that I will try to start working on. There's been a Pull Request to add a basic Dvar switch but I would like to flesh it out a little bit more than that with a menu option and something more like the insta kill toggle, where you can just toggle on/off an endless chain of special rounds (and maybe a little something for the Napalms/Shriekers on Shang, as they are currently disabled I think). This will require me to go map-by-map to make sure its working though, so this will take me some time.
