### ISSUE TITLE
Doors opened on Moon are outdated

### ISSUE THREAD

**Issue by llPh3NiXll** [5and5/BO1-StratTester#28]
On Moon, nowadays, players are using BDSM strategy, which requires the door between Stamin-up and the BDSM window to be closed.
At the moment, when you activate "open doors" in the settings, doors setup is still the one used for spawn strategy used back in days.

Thanks.

**Comment by 5and5** [comment]
I opened all doors other than the stam to one window.

bc8c4735e880a358b74eeea0fa3771740ed36203
