### ISSUE TITLE
Doors opened on Call of the Dead are wrong

### ISSUE THREAD

**Issue by llPh3NiXll** [5and5/BO1-StratTester#29]
On Call of the Dead, the door setup is wrong. Two doors should remain closed :
- the boat at the beach (players can open it manually depending on their trade setup)
- the lighthouse door close to the AK74u 
At the moment, when you activate "open doors" in the settings, both doors are opened.

Thanks.

**Comment by 5and5** [comment]
I closed all beach doors and cave in case anyone wants to test strats with that door setup.

5ffe051a3989ab472d0c059a0a5d23e7acb539b4
