### ISSUE TITLE
Give players Claymores / Betties

### ISSUE THREAD

**Issue by llPh3NiXll** [5and5/BO1-StratTester#30]
Currently, when a player is setting the option to get weapons, he is not getting Claymores or Betties. This should be changed since there is a huge chance that players would have them during strategies.

Thanks.

**Comment by 5and5** [comment]
I added both claymores and betties to the give list.

77eae3e15d2d7f12685b382842609eb4a6bc481a
f6fb1e05f940acd7c41471c1042fd452c1dceb05
