### ISSUE TITLE
Moon without sound or low sound when you starts with "power on"

### ISSUE THREAD

**Issue by Hefesto0** [5and5/BO1-StratTester#35]
For some reason, sometimes when u start moon and the power option is ON in the game menu, the game sound is zero ou too low, usually it happens on Coop for one or both players, I didn't test with 3/4p.

Thanks

**Comment by TTS4life** [comment]
Yea I'm aware of this one, just been low on my priority list to fix. Does putting on the PES and then taking it off fix it as a temp fix in game?

**Comment by Hefesto0** [comment]
Nope, it isnt a fix
