### ISSUE TITLE
Fixing astro spawn + other quality of life stuff 

### ISSUE THREAD

**Issue by zombiw** [5and5/BO1-StratTester#40]
Gooday, So on moon getting the astronaut to spawn in is quite difficult sometimes, requiring you to go into nml a few times. If its possible I think it would be useful to make it so he instantly spawns in when you click enable (so you can have him spawn near you instead of in spawn), and have him blow up when you disable him. Also he doesn't have a name tag but that's besides the point. 

Other quality of life stuff I think would be useful: 
-Round end button (instantly finishes round when pressed)
-Average kills counter with all wonder weapons (Like the one lveez made for the waffe) 
-Making Moons auto door opening more friendly towards bdsm players

Thanks for the most useful learning too guys!   :D

**Comment by lveez** [comment]
I believe 5and5 has fixed the moon doors for v2.3 and I have fixed the astro spawning for the next release we do. I will leave open as there are other suggestions that haven't been added yet.
