### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by Hefesto0** [5and5/BO1-StratTester#41]
It's not a issue, only suggestions

Sometimes is interesting practice a specific scenario because it's rare ou too hard.
BO1 has commands for save and load your state, does have some way to make a easy option to bind this?

And the other suggestion, IDK if it's possible, but I guess interesting to make a "perfect trade" option, when ON, 1 hit trade or 100% drop chance by gersh, it can help to measure the sph for long round with many trades

**Comment by Zi0MIX** [comment]
Yeah you can make binds for save states in BO1, not sure what that has to do with strattester, it'd be independently done in the config

As for the other suggestion, i added perfect trade options as well as infinite ammo option (which will constantly refill your reserve ammo), that should help for SPH measuring. Will be available for next release
